// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihhcvsoucjlprppuymdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaGN2c291Y2pscHJwcHV5bWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzgzMTQsImV4cCI6MjA2MjM1NDMxNH0.FgC9Qp--4B3IBMo55EzfkicGNE0cMS_dAp_I9xugBYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);